services: docker

before_install:
 - docker run --cidfile /tmp/id -it -d anselmolsm/travis_ci_deps:ubuntu1604 /bin/bash
 - tar cf csd.tar * && docker cp csd.tar $(cat /tmp/id):/tmp/

script:  
 - docker exec -i $(cat /tmp/id) /bin/bash -c "cd /tmp/ && tar xf csd.tar && ./autogen.sh"
 - docker exec -i $(cat /tmp/id) /bin/bash -c "cd /tmp/ && ./configure && make -j"
